version: "3.8"
services:
  uptime-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - uptime-backend

  uptime-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ./status.json:/app/status.json
      - ./uptime-daily.json:/app/uptime-daily.json
